<?php

namespace app\components\widgets\custom;

use app\components\AppConfig;
use app\modules\imagemanager\models\Image;
use common\sys\repository\blog\models\BlogArticles;
use yii\base\Widget;

class BlogSidebarRight extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $last_artical = BlogArticles::find()
            ->select(['id', 'alias', 'title', 'summary'])
            ->where(['is_top' => 1])
            ->one();
        $last_artical_img = Image::findOne([
            'content_id' => $last_artical->id,
            'content_type_id' => AppConfig::Image_ContentType_BlogArticle,
            'content_field_id' => AppConfig::Image_ContentField_BlogArticle,
        ]);

        return $this->render(
            'blog-sidebar-right', [
                'last_artical' => $last_artical,
                'last_artical_img' => $last_artical_img,
            ]
        );
    }
}