<?php

namespace app\components\widgets\custom;

use common\sys\core\testimonials\TestimonialsInfoService;
use yii\base\Widget;

class BlogSidebarRight extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $testimonialsService = new TestimonialsInfoService();

        return $this->render(
            'blog-sidebar-right', [
                'reviews' => $testimonialsService->get_testimonials_is_top(3),
            ]
        );
    }
}