<?php

namespace app\components\widgets\custom;

use common\sys\repository\landing\models\City;
use common\sys\repository\landing\models\Country;
use yii\base\Widget;

class LandingHeaderMenu extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $countries = Country::find()
            ->select(['id', 'alias', 'name'])
            ->all();
        $cities = City::find()
            ->select(['id', 'alias', 'name'])
            ->all();

        return $this->render(
            'landing-header-menu', [
                'countries' => $countries,
                'cities'    => $cities
            ]
        );
    }
}