<?php

namespace app\components\widgets\custom;

use app\components\AppConfig;
use app\modules\imagemanager\models\Image;
use common\sys\core\testimonials\TestimonialsInfoService;
use common\sys\repository\blog\models\BlogArticles;
use yii\base\Widget;

class LandingSidebarRight extends Widget
{
    public $summary_sidebar;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $last_artical = BlogArticles::find()
            ->select(['id', 'alias', 'title', 'summary'])
            ->where(['is_top' => 1])
            ->one();
        $last_artical_img = Image::findOne([
            'queue' => 0,
            'content_id' => $last_artical->id,
            'content_type_id' => AppConfig::Image_ContentType_BlogArticle,
            'content_field_id' => AppConfig::Image_ContentField_BlogArticle,
        ]);

        $testimonialsService = new TestimonialsInfoService();

        return $this->render(
            'landing-sidebar-right', [
                'summary_sidebar' => $this->summary_sidebar,
                'last_artical' => $last_artical,
                'last_artical_img' => $last_artical_img,
                'review' => current($testimonialsService->get_testimonials_is_top(1)),
            ]
        );
    }
}