<?php

namespace app\components\widgets\imagemanager;

use yii\base\Widget;

class ImageFormWidget extends Widget
{
    public $config;
    public $images;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render(
            'image',
            [
                'config' => $this->config,
                'images' => $this->images
            ]
        );
    }
}