<?php

return [
    '<action:(login|logout)>' => 'site/<action>',
    'page/about-us-best-deals-business-first-tickets' => 'static-page/about',
    'page/last-minute-deals' => 'static-page/last-minute-deals',
    'page/best-business-class-deals-cheap' => 'static-page/corporate-account',
    'page/testimonials-business-first-class-tickets' => 'static-page/testimonials',
    'service/first-class-specials' => 'service/first-class',
    'service/one-way-business-class-tickets' => 'service/business-class',
    'service/cheap-hotels-book-discount' => 'service/hotel',
    'tools/flight-tracker' => 'tools/flight-tracker',
    'tools/first-class-cheap-business' => 'tools/visa',
    'tools/request-cheap-business-quote' => 'tools/request-quote',
    'flight-request/<request_number:\d+>' => 'request/flight-request-accepted',
    '<controller:(request)>' => '<action:(hotel)>',
    '<controller:(blog|travel-tips)>/page/<page:\d+>' => '<controller>/list',
    '<controller:(blog|travel-tips)>' => '<controller>/list',
    'blog/ListApi' => 'blog/list-api',
    'sitemap/page/<page:\d+>' => 'site-map-page/index',
    'sitemap'=>'site-map-page/index',
    'sitemap.xml'=>'sitemap/index',
    '<controller:(continent|country|city|airline|blog|travel-tips)>/<alias:[0-9a-zA-Z_\-]+>' => '<controller>/index',
    'adminarea' => 'admin/home/index',
    '<alias:[0-9a-zA-Z_\-]+>' => 'direction-city/index',
    'adminarea/<controller:(blog|continent|country|city|airline|testimonials|travel-tips|direction-city|static-page|subscriber|blocked-email|flight-emails)>' => 'admin/<controller>/index',
    'adminarea/<controller:(blog|continent|country|city|airline|testimonials|travel-tips|direction-city|blocked-email)>/<action:(create)>' => 'admin/<controller>/<action>',
    'adminarea/<controller:(blog|continent|country|city|airline|testimonials|travel-tips|direction-city|static-page|blocked-email)>/<action:(edit|delete)>/<id:\d+>' => 'admin/<controller>/<action>',
    'adminarea/travel-tips/<id:\d+>/<action:(travel-tips-attactions|create-travel-tips-attaction)>' => 'admin/travel-tips/<action>',
    'adminarea/travel-tips/<id:\d+>/<action:(edit-travel-tips-attaction|delete-travel-tips-attaction)>/<travel_tip_attaction_id:\d+>' => 'admin/travel-tips/<action>',
    'adminarea/request-flight/<id:\d+>/<action:(request-flight-details)>' => 'admin/request-flight/<action>',
    'adminarea/<controller:(xml-data)>/<action:(subscribers|blog|continent|country|city|airline|travel-tips|traveltipsattractions|directions-cities|need-img|image)>' => 'admin/<controller>/<action>',
];