<?php

namespace app\components\widgets\request;

use app\components\AppConfig;
use yii;
use yii\base\Widget;

class FlightRequestMin extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $flight_request_max_model = new \common\sys\models\request\FlightRequestMax();

        $cabin_class = [
            AppConfig::Cabin_Class_Business => 'Business',
            AppConfig::Cabin_Class_First => 'First'
        ];

        $trip_variants = [
            AppConfig::Type_Trip_Round_Trip => 'Round-trip',
            AppConfig::Type_Trip_One_Way => 'One-way',
            AppConfig::Type_Trip_Multi_City => 'Multi-city'
        ];

        $number_persones = [
            1 => 'Travelers 1',
            2 => 'Travelers 2',
            3 => 'Travelers 3',
            4 => 'Travelers 4',
            5 => 'Travelers 5',
            6 => 'Travelers 6',
            7 => 'Travelers 7',
            8 => 'Travelers 8',
        ];

        return $this->render(
            'flight-request-min', [
                'cabin_class' => $cabin_class,
                'number_persones' => $number_persones,
                'trip_variants' => $trip_variants,
                'model' => $flight_request_max_model
            ]
        );
    }
}