<?php

namespace app\components\widgets\request;

use app\components\AppConfig;
use yii;
use yii\base\Widget;

class FlightRequestMax extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $flight_request_max_model = new \common\sys\models\request\FlightRequestMax();

        $cabin_class = [
            AppConfig::Cabin_Class_Business => 'Business',
            AppConfig::Cabin_Class_First => 'First'
        ];

        $number_persones = [
            1 => '1 Person(s)',
            2 => '2 Person(s)',
            3 => '3 Person(s)',
            4 => '4 Person(s)',
            5 => '5 Person(s)',
            6 => '6 Person(s)',
            7 => '7 Person(s)',
            8 => '8 Person(s)',
        ];

        return $this->render(
            'flight-request-max', [
                'cabin_class' => $cabin_class,
                'number_persones' => $number_persones,
                'model' => $flight_request_max_model
            ]
        );
    }
}