<?php

namespace app\components\widgets\request;

use common\sys\models\request\RequestQuote;
use yii;
use yii\base\Widget;

class RequestQuoteForm extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $request_quote_model = new RequestQuote();
        return $this->render('request-quote', [
            'model' => $request_quote_model,
        ]);
    }
}