<?php

namespace app\components\widgets\request;

use yii;
use yii\base\Widget;

class RequestSubscriber extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $model = new \common\sys\repository\subscribers\models\Subscribers();
        return $this->render('request-subscriber', [
            'model' => $model
        ]);
    }
}