<?php

namespace app\components\widgets\request;

use common\sys\models\request\RequestCorporateAccounts;
use yii;
use yii\base\Widget;

class RequestCorporateAcoounts extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $request_corporate_accounts_model = new RequestCorporateAccounts();
        return $this->render('corporate-accounts', [
            'model' => $request_corporate_accounts_model,
        ]);
    }
}