<?php

namespace app\components\widgets\request;

use yii;
use yii\base\Widget;
use frontend\models\SupportForm;

class SupportFormWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        $support_form_model = new SupportForm();

        return $this->render(
            'support-form', [
                'model' => $support_form_model,
            ]
        );
    }
}