<?php

namespace app\components\widgets\admincontentfilter;


use app\components\AdminAppConfig;
use yii\base\Widget;

class AdminContentFilterWidget extends Widget
{
    public $page;
    public $filter_values;
    public $parametrs;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        if($this->page == AdminAppConfig::Filter_Airline_Page) {
            return $this->render(
                'filters_airline',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_Blog_Page) {
            return $this->render(
                'filters_blog',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_City_Page) {
            return $this->render(
                'filters_city',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_Country_Page) {
            return $this->render(
                'filters_country',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_Continent_Page) {
            return $this->render(
                'filters_continent',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_Testimonials_Page) {
            return $this->render(
                'filters_testimonials',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_Travel_Tips_Page) {
            return $this->render(
                'filters_travel_tips',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        elseif ($this->page == AdminAppConfig::Filter_Direction_City_Page) {
            return $this->render(
                'filters_direction_city',
                [
                    'page' => $this->page,
                    'filter_values' => $this->filter_values,
                    'parametrs' => $this->parametrs,
                ]
            );
        }
        return $this->render(
            'filters',
            [
                'page' => $this->page,
                'filter_values' => $this->filter_values,
                'parametrs' => $this->parametrs,
            ]
        );
    }
}