<?php

namespace app\components\widgets\adminmenu;


use yii\base\Widget;

class AdminMenuWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        return $this->render(
            'adminmenu'
        );
    }
}